project: diffusion 
name: tiny_imagenet
wandb: false

jittor:
  use_cuda: true
  seed: 66 

lr: 0.00002
resume: null
start_epoch: 0
epochs: 1000
print_freq: 20 # print and log every i iteration (batch)
save_wandb_image_freq: 100
sample_freq: 20
save_dir: ./save # save_dir is 'save_dir/name'
save_freq: 50 # save ckpt

diffusion:
  beta_schedule: cosine
  timesteps: 1000 
  image_size: 64 
  channels: 3
  loss_type: l1
  objective: pred_noise # or pred_x0
  # log_every_t: 100 
  use_ema: true
  ckpt_path: null
  load_ema_model: false ##
  clip_denoised: true
  unet_config: 
    image_size: 64
    in_channels: 3
    model_channels: 128
    out_channels: 3
    num_res_blocks: 3
    attention_resolutions: []
    dropout: 0.3
    channel_mult:
    - 1
    - 2
    - 4
    - 8
    num_heads: 4
  
data:
  root: /nas/datasets/tiny_imagenet_200
  batch_size: 128
  num_workers: 8